server:
  port: 8086

spring:
  application:
    name: auth-service
  datasource:
    # Apunta a la base de datos PostgreSQL del entorno offline
    url: jdbc:postgresql://postgres-db-offline:5432/ecopila_db_offline
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history_auth
application:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET_KEY}
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always