# render.yaml - VERSIÓN FINAL OFFLINE (usar con sync en Render)

envVarGroups:
  - name: ecopila-shared-config
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: offline
      - key: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
        value: 1.0

databases:
  - name: postgres-db-offline
    plan: free
    postgresMajorVersion: 14
    ipAllowList: []

services:
  - type: redis
    name: redis-offline
    plan: free
    ipAllowList: []

  - type: web
    name: eureka-service-offline
    plan: free
    env: docker
    dockerfilePath: ./eureka-service/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config

  - type: web
    name: symmetricds-master-offline
    plan: free
    env: docker
    dockerfilePath: ./symmetricds/master/Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - fromGroup: ecopila-shared-config
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db-offline
          property: connectionString
      - key: SYMMETRIC_URL
        value: https://symmetricds-master-offline.onrender.com

  - type: web
    name: gateway-offline
    plan: free
    env: docker
    dockerfilePath: ./gateway/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - fromGroup: ecopila-secrets
      - key: EUREKA_URI
        value: http://eureka-service-offline:8761/eureka
      - key: SPRING_DATA_REDIS_URL
        fromService:
          type: redis
          name: redis-offline
          property: connectionString

  - type: web
    name: auth-service-offline
    plan: free
    env: docker
    dockerfilePath: ./auth-service/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - fromGroup: ecopila-secrets
      - key: EUREKA_URI
        value: http://eureka-service-offline:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: postgres-db-offline
          property: connectionString

  - type: web
    name: producto-service-offline
    plan: free
    env: docker
    dockerfilePath: ./microservicio_producto/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-offline:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: postgres-db-offline
          property: connectionString

  - type: web
    name: proveedor-service-offline
    plan: free
    env: docker
    dockerfilePath: ./microservicio_proveedor/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-offline:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: postgres-db-offline
          property: connectionString

  - type: web
    name: tipo-producto-service-offline
    plan: free
    env: docker
    dockerfilePath: ./microservicio_tipo_producto/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-offline:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: postgres-db-offline
          property: connectionString

  - type: web
    name: dolar-service-offline
    plan: free
    env: docker
    dockerfilePath: ./microservicio_dolar/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-offline:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: postgres-db-offline
          property: connectionString
