# render.yaml - VERSIÓN DE DEPURACIÓN MÍNIMA

# Definición de la base de datos
databases:
  - name: postgres-db-online
    plan: free
    postgresMajorVersion: 14

# Definición de UN solo servicio para probar
services:
  - type: web
    name: eureka-service-online
    plan: free
    env: docker
    # Asegúrate de que la ruta a tu Dockerfile es correcta
    dockerfilePath: ./eureka-service/Dockerfile
    dockerContext: .
    # Aquí está el healthCheck que nos da problemas
    healthCheck:
      path: /actuator/health
      initialDelaySeconds: 45
