# render.yaml - Configuración para desplegar EcopilaStock en Render

# Grupos de variables de entorno para compartir entre servicios
envVarGroups:
  - name: ecopila-shared-config
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
        value: 1.0
  - name: ecopila-secrets
    secretGroup: ecopila-secrets # Debes crear este grupo en Render y añadir JWT_BASE64_SECRET

# --- CORRECCIÓN PRINCIPAL ---
# 1. Las bases de datos se definen en su propia sección 'databases', no en 'services'.
databases:
  - name: postgres-db-online
    plan: free
    postgresMajorVersion: 14
    ipAllowList: [] # Permite acceso desde cualquier servicio de tu cuenta

# 2. Los servicios web, workers y Redis van en la sección 'services'.
services:
  - type: redis
    name: redis-online
    plan: free
    ipAllowList: []

  - type: web
    name: eureka-service-online
    plan: free
    env: docker
    dockerfilePath: ./eureka-service/Dockerfile
    dockerContext: .
    healthCheck:
      path: /actuator/health
      initialDelaySeconds: 45
    envVars:
      - fromGroup: ecopila-shared-config

  - type: web
    name: symmetricds-master
    plan: free
    env: docker
    dockerfilePath: ./symmetricds/master/Dockerfile
    dockerContext: .
    healthCheck:
      path: /
      initialDelaySeconds: 90
    envVars:
      - fromGroup: ecopila-shared-config
      # Las referencias 'fromService' con 'type: postgres' son correctas.
      - key: PG_HOST
        fromService:
          type: postgres
          name: postgres-db-online
          property: host
      - key: PG_USER
        fromService:
          type: postgres
          name: postgres-db-online
          property: user
      - key: PGPASSWORD
        fromService:
          type: postgres
          name: postgres-db-online
          property: password
      - key: PG_DB
        fromService:
          type: postgres
          name: postgres-db-online
          property: database
      - key: SYMMETRIC_URL
        value: https://symmetricds-master.onrender.com

  - type: web
    name: gateway
    plan: free
    env: docker
    dockerfilePath: ./gateway/Dockerfile
    dockerContext: .
    healthCheck:
      path: /actuator/health
      initialDelaySeconds: 60
    envVars:
      - fromGroup: ecopila-shared-config
      - fromGroup: ecopila-secrets
      - key: EUREKA_URI
        value: http://eureka-service-online:8761/eureka
      - key: SPRING_DATA_REDIS_URL
        fromService:
          type: redis
          name: redis-online
          property: connectionString

  - type: web
    name: auth-service-online
    plan: free
    env: docker
    dockerfilePath: ./auth-service/Dockerfile
    dockerContext: .
    healthCheck: { path: /actuator/health, initialDelaySeconds: 60 }
    envVars:
      - fromGroup: ecopila-shared-config
      - fromGroup: ecopila-secrets
      - key: EUREKA_URI
        value: http://eureka-service-online:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService: { type: postgres, name: postgres-db-online, property: connectionString }

  - type: web
    name: producto-service-online
    plan: free
    env: docker
    dockerfilePath: ./microservicio_producto/Dockerfile
    dockerContext: .
    healthCheck: { path: /actuator/health, initialDelaySeconds: 60 }
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-online:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService: { type: postgres, name: postgres-db-online, property: connectionString }

  - type: web
    name: proveedor-service-online
    plan: free
    env: docker
    dockerfilePath: ./microservicio_proveedor/Dockerfile
    dockerContext: .
    healthCheck: { path: /actuator/health, initialDelaySeconds: 60 }
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-online:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService: { type: postgres, name: postgres-db-online, property: connectionString }

  - type: web
    name: tipo-producto-service-online
    plan: free
    env: docker
    dockerfilePath: ./microservicio_tipo_producto/Dockerfile
    dockerContext: .
    healthCheck: { path: /actuator/health, initialDelaySeconds: 60 }
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-online:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService: { type: postgres, name: postgres-db-online, property: connectionString }

  - type: web
    name: dolar-service-online
    plan: free
    env: docker
    dockerfilePath: ./microservicio_dolar/Dockerfile
    dockerContext: .
    healthCheck: { path: /actuator/health, initialDelaySeconds: 60 }
    envVars:
      - fromGroup: ecopila-shared-config
      - key: EUREKA_URI
        value: http://eureka-service-online:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromService: { type: postgres, name: postgres-db-online, property: connectionString }
