services:
  - type: pserv
    name: postgres-db-online
    plan: free
    env: postgres
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  - type: web
    name: symmetricds-master
    plan: free
    env: docker
    dockerfilePath: ./symmetricds/master/Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - fromGroup: ecopila-shared-config
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db-online
          property: connectionString
      - key: SYMMETRIC_URL
        value: https://symmetricds-master.onrender.com

  - type: web
    name: symmetricds-node
    plan: free
    env: docker
    dockerfilePath: ./symmetricds/node/Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - fromGroup: ecopila-shared-config
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db-online
          property: connectionString
      - key: SYMMETRIC_URL
        value: https://symmetricds-node.onrender.com

  - type: web
    name: eureka-server
    plan: free
    env: docker
    dockerfilePath: ./eureka/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config

  - type: web
    name: gateway-server
    plan: free
    env: docker
    dockerfilePath: ./gateway/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config

  - type: web
    name: microservicio-admin
    plan: free
    env: docker
    dockerfilePath: ./microservicio-admin/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db-online
          property: connectionString

  - type: web
    name: microservicio-user
    plan: free
    env: docker
    dockerfilePath: ./microservicio-user/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db-online
          property: connectionString

  - type: web
    name: microservicio-monopatin
    plan: free
    env: docker
    dockerfilePath: ./microservicio-monopatin/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db-online
          property: connectionString

  - type: web
    name: microservicio-viaje
    plan: free
    env: docker
    dockerfilePath: ./microservicio-viaje/Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - fromGroup: ecopila-shared-config
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db-online
          property: connectionString

envVarGroups:
  - name: ecopila-shared-config
    envVars:
      - key: EUREKA_SERVER
        value: https://eureka-server.onrender.com/eureka
      - key: GATEWAY_SERVER
        value: https://gateway-server.onrender.com
